name: post to api

on: [push]

jobs:
  
  deploy-params-tables:

    runs-on: ubuntu-latest

    steps:
      - name: post to api

        run: |-
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "authorization: Bearer ${{secrets.GIT_ACCESS_TOKEN}}" \
            --header 'content-type: application/json' \
            --url https://api.github.com/repos/vitorstone/test-workflow-2/dispatches \
            -d '{"event_type":"push-staging"}'